name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CHERE_INVOKING: 1

jobs:
  test:
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - uses: actions/checkout@v2
        with:
          repository: gap-packages/profiling
      - uses: actions/checkout@v2
        with:
          path: this-action/
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: 'io'
      - uses: ./this-action/
