name: CI

# Trigger the workflow on push to main, or on pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # the order of the checkout actions is important because all contents of
      # the target folder of the checkout action is removed
      - uses: actions/checkout@v5
        with:
          repository: gap-packages/profiling
      - uses: actions/checkout@v5
        with:
          path: this-action/
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: 'io'
      - uses: ./this-action/
